In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(
    "../datasets/raw/fake reviews dataset.csv"
)

df2 = pd.read_csv(
    "../datasets/raw/public_reviews_dataset_cleaned.csv"
)

print("Dataset 1:", df1.shape)
print("Dataset 2:", df2.shape)

print("\nDataset 1 Labels:")
print(df1["label"].value_counts())

C:\Users\KRISH MALHOTRA\AppData\Local\Temp\ipykernel_29936\732254822.py:5: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(

Dataset 1: (40432, 4)
Dataset 2: (381734, 23)

Dataset 1 Labels:
label
CG    20216
OR    20216
Name: count, dtype: int64

In [3]:
print(df1.columns)

Index(['category', 'rating', 'label', 'text_'], dtype='object')

In [4]:
print(df2.columns)

Index(['asin', 'review_id', 'reviewer_id', 'review_title', 'review_text',
       'review_rating', 'review_date', 'product_title', 'product_url',
       'number_of_helpful', 'number_of_photos', 'photo_thumbnail_urls',
       'photo_fullsize_urls', 'asin_url', 'review_url', 'reviewer_url',
       'fake_review_campaign_start_date', 'fake_review_product',
       'reviewer_classified_fake', 'reviewer_classified_honest',
       'reviewer_labeled_fake', 'reviewer_labeled_honest',
       'review_is_removed_by_amazon'],
      dtype='object')

In [5]:
df1.head()

,category,rating,label,text_
0,Home_and_Kitchen_5,5.0,CG,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5.0,CG,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5.0,CG,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1.0,CG,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5.0,CG,Very nice set. Good quality. We have had the s...

In [6]:
df2.head()

,asin,review_id,reviewer_id,review_title,review_text,review_rating,review_date,product_title,product_url,number_of_helpful,...,asin_url,review_url,reviewer_url,fake_review_campaign_start_date,fake_review_product,reviewer_classified_fake,reviewer_classified_honest,reviewer_labeled_fake,reviewer_labeled_honest,review_is_removed_by_amazon
0,B003MROHZW,R2RDK8SL1QXN8I,AHAHNBDF4GJ26DAL3VS7MGJDNCKA,Dog muzzle,Serves it purpose.,5,2016-01-22,Downtown Pet Supply Quick Fit Dog Muzzle with ...,https://www.amazon.com/Small-Muzzle-Downtown-P...,0.0,...,https://www.amazon.com/dp/B003MROHZW,https://www.amazon.com/gp/customer-reviews/R2R...,https://www.amazon.com/gp/profile/amzn1.accoun...,2020-02-08,True,True,False,0.0,0.0,0.0
1,B008DZ6JPO,R1CSQAGJT0JXO7,AEZ2DKBYDRPE5O3ENPHV3XRJBMGQ,Awesome product!!,I use this ALL the time!! Looks really nice ...,5,2017-09-25,Winsome 92436 Luggage Rack with Shelf,https://www.amazon.com/Winsome-92436-Luggage-R...,0.0,...,https://www.amazon.com/dp/B008DZ6JPO,https://www.amazon.com/gp/customer-reviews/R1C...,https://www.amazon.com/gp/profile/amzn1.accoun...,NaN,True,True,False,0.0,0.0,0.0
2,B008DZ6JPO,R1XD30XZ3BXO7F,AF52D4YPSCPGLWNYVXZDGG525R2A,Good quality. Color is nice just like the pict...,Well made product. I purchased that refurbishe...,5,2018-11-14,Winsome 92436 Luggage Rack with Shelf,https://www.amazon.com/Winsome-92436-Luggage-R...,0.0,...,https://www.amazon.com/dp/B008DZ6JPO,https://www.amazon.com/gp/customer-reviews/R1X...,https://www.amazon.com/gp/profile/amzn1.accoun...,NaN,True,True,False,0.0,0.0,0.0
3,B008DZ6JPO,R3L61UVBYHB2QK,AFPXQX5HARB76E7GOIUTU32332KQ,Nice Looking and Easy Set Up,"Nice looking, sturdy and easy to set up.",5,2020-02-04,Winsome 92436 Luggage Rack with Shelf,https://www.amazon.com/Winsome-92436-Luggage-R...,0.0,...,https://www.amazon.com/dp/B008DZ6JPO,https://www.amazon.com/gp/customer-reviews/R3L...,https://www.amazon.com/gp/profile/amzn1.accoun...,NaN,True,True,False,0.0,0.0,0.0
4,B00GIHF6AS,R36G7QSYO7QRAS,AFP3AD7L3KWYHHQ4UQAIWJAZX7FQ,Cut pvc like fruit.,", Your browser does not support HTML5 video...",5,2020-03-10,"MAXPOWER Automatic PVC Pipe Cutter, Ratchet-ty...",https://www.amazon.com/MAXPOWER-Cortatubos-aut...,4.0,...,https://www.amazon.com/dp/B00GIHF6AS,https://www.amazon.com/gp/customer-reviews/R36...,https://www.amazon.com/gp/profile/amzn1.accoun...,2020-02-14,True,True,False,1.0,0.0,0.0

In [7]:
for col in [
    "fake_review_product",
    "reviewer_classified_fake",
    "reviewer_classified_honest",
    "reviewer_labeled_fake",
    "reviewer_labeled_honest",
    "review_is_removed_by_amazon"
]:
    print("\n", col)
    print(df2[col].value_counts(dropna=False).head(20))

 fake_review_product
fake_review_product
False    221181
True     160553
Name: count, dtype: int64

 reviewer_classified_fake
reviewer_classified_fake
False    324067
True      57667
Name: count, dtype: int64

 reviewer_classified_honest
reviewer_classified_honest
False    359120
True      22614
Name: count, dtype: int64

 reviewer_labeled_fake
reviewer_labeled_fake
NaN    301453
0.0     58143
1.0     22138
Name: count, dtype: int64

 reviewer_labeled_honest
reviewer_labeled_honest
NaN    301453
0.0     69479
1.0     10802
Name: count, dtype: int64

 review_is_removed_by_amazon
review_is_removed_by_amazon
0.0    256614
NaN     86175
1.0     38945
Name: count, dtype: int64

In [8]:
print(df2["reviewer_labeled_fake"].sum())
print(df2["reviewer_labeled_honest"].sum())

22138.0
10802.0

In [9]:
print(df2["reviewer_labeled_fake"].value_counts())
print(df2["reviewer_labeled_honest"].value_counts())

reviewer_labeled_fake
0.0    58143
1.0    22138
Name: count, dtype: int64
reviewer_labeled_honest
0.0    69479
1.0    10802
Name: count, dtype: int64

In [10]:
df2[
    df2["reviewer_labeled_fake"] == 1
][[
    "review_text",
    "review_rating"
]].head(10)

                                          review_text  review_rating
4     ,  Your browser does not support HTML5 video...              5
5   Got this to cut the pipe behind toilet that wa...              5
9     Light is very well packaged to protect it du...              5
10    I am using this for my aquarium. The light i...              5
11    ,  Your browser does not support HTML5 video...              5
12    Very happy with the performance of this ligh...              5
13    Very bright. Throws good light. The white bo...              5
14    Very bright and works great!! Good price. Lo...              5
18  This is a very compact and high performance LE...              5
20  These have been working great. I always have i...              5

In [11]:
df2[
    [
        "reviewer_labeled_fake",
        "reviewer_labeled_honest"
    ]
].isna().sum()

reviewer_labeled_fake      301453
reviewer_labeled_honest    301453
dtype: int64

In [12]:
print(df2["reviewer_labeled_honest"].value_counts(dropna=False))

reviewer_labeled_honest
NaN    301453
0.0     69479
1.0     10802
Name: count, dtype: int64

In [13]:
print(
    df2[
        ["reviewer_labeled_fake",
         "reviewer_labeled_honest"]
    ].head()
)

   reviewer_labeled_fake  reviewer_labeled_honest
0                    0.0                      0.0
1                    0.0                      0.0
2                    0.0                      0.0
3                    0.0                      0.0
4                    1.0                      0.0

In [14]:
fake_reviews = df2[
    df2["reviewer_labeled_fake"] == 1
]

genuine_reviews = df2[
    df2["reviewer_labeled_honest"] == 1
]

In [15]:
print(
    df2["reviewer_labeled_honest"]
    .value_counts(dropna=False)
)

reviewer_labeled_honest
NaN    301453
0.0     69479
1.0     10802
Name: count, dtype: int64

In [16]:
fake_reviews = df2[
    df2["reviewer_labeled_fake"] == 1
]

genuine_reviews = df2[
    df2["reviewer_labeled_honest"] == 1
]

In [17]:
print(fake_reviews.shape)
print(genuine_reviews.shape)

print(fake_reviews["review_text"].head(3))

print(genuine_reviews["review_text"].head(3))

(22138, 23)
(10802, 23)
4      ,  Your browser does not support HTML5 video...
5    Got this to cut the pipe behind toilet that wa...
9      Light is very well packaged to protect it du...
Name: review_text, dtype: object
322                  Very well made sleek computer mouse
502      It was not very difficult to adjust to. It's...
505      I really like this new mouse! By the way, I ...
Name: review_text, dtype: object